# Generated by Django 5.2.8 on 2026-02-21 11:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=30)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('current_job', models.CharField(blank=True, default='', max_length=255)),
                ('sector', models.CharField(blank=True, default='', max_length=255)),
                ('rank', models.CharField(blank=True, default='', max_length=100)),
                ('start_date', models.CharField(blank=True, default='', max_length=50)),
                ('current_school', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('applicants', 'Applicants'), ('schools', 'Schools')], max_length=20)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('returned', 'Returned'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('fallback_choice', models.CharField(blank=True, choices=[('admin_assign', 'توجيه من الإدارة'), ('stay_current', 'البقاء في المدرسة الحالية')], default='', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.applicant')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.importbatch'),
        ),
        migrations.CreateModel(
            name='SchoolVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_no', models.CharField(blank=True, default='', max_length=50)),
                ('school_name', models.CharField(max_length=255)),
                ('stage', models.CharField(blank=True, default='', max_length=100)),
                ('sector', models.CharField(blank=True, default='', max_length=255)),
                ('establishment_status', models.CharField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('education_type', models.CharField(blank=True, default='', max_length=100)),
                ('manager_national_id', models.CharField(blank=True, default='', max_length=20)),
                ('manager_name', models.CharField(blank=True, default='', max_length=255)),
                ('students_total', models.IntegerField(default=0)),
                ('classes_total', models.IntegerField(default=0)),
                ('students_metric', models.IntegerField(default=0)),
                ('class_metric', models.IntegerField(default=0)),
                ('stage_code', models.CharField(blank=True, default='', max_length=50)),
                ('stage_metric', models.IntegerField(default=0)),
                ('deputy_staff', models.IntegerField(default=0)),
                ('deputy_existing', models.IntegerField(default=0)),
                ('deputy_need', models.IntegerField(default=0)),
                ('is_open', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefs', to='portal.application')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.schoolvacancy')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddIndex(
            model_name='schoolvacancy',
            index=models.Index(fields=['sector', 'gender'], name='portal_scho_sector_8a4916_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolvacancy',
            index=models.Index(fields=['school_name'], name='portal_scho_school__b4b7d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicationpreference',
            constraint=models.UniqueConstraint(fields=('application', 'rank'), name='uniq_app_rank'),
        ),
        migrations.AddConstraint(
            model_name='applicationpreference',
            constraint=models.UniqueConstraint(fields=('application', 'vacancy'), name='uniq_app_vacancy'),
        ),
    ]
