# Generated by Django 5.2.8 on 2026-02-21 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admin_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='admin_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wakil_admin_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='admin_decision',
            field=models.CharField(blank=True, choices=[('', '—'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('returned', 'مُعاد للتعديل')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('returned', 'Returned'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['national_id'], name='portal_appl_nationa_16a4b7_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['sector', 'gender'], name='portal_appl_sector_958851_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='portal_appl_status_130f74_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['admin_decision'], name='portal_appl_admin_d_a53b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['submitted_at'], name='portal_appl_submitt_20304a_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolvacancy',
            index=models.Index(fields=['ministry_no'], name='portal_scho_ministr_37d8a9_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolvacancy',
            index=models.Index(fields=['deputy_need'], name='portal_scho_deputy__eecb07_idx'),
        ),
    ]
