# Generated by Django 5.2.8 on 2026-02-22 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_application_achieved_at_application_achieved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['full_name'], name='portal_appl_full_na_d3a4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['achieved_at'], name='portal_appl_achieve_3a0985_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['admin_decided_at'], name='portal_appl_admin_d_fd87d3_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationpreference',
            index=models.Index(fields=['rank'], name='portal_appl_rank_d6b2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationpreference',
            index=models.Index(fields=['vacancy'], name='portal_appl_vacancy_5eea19_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolvacancy',
            index=models.Index(fields=['is_open'], name='portal_scho_is_open_e1d831_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('achieved_pref__isnull', True), ('admin_decision', 'approved'), _connector='OR'), name='achieved_requires_admin_approved'),
        ),
    ]
