# Generated by Django 5.2.8 on 2026-02-22 19:55

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_applicant_portal_appl_full_na_d3a4b8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='applicationpreference',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicationpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='schoolvacancy',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='schoolvacancy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='achieved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['is_active'], name='portal_appl_is_acti_8f7216_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['admin_decision', 'achieved_at'], name='portal_appl_admin_d_f3db39_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationpreference',
            index=models.Index(fields=['application', 'rank'], name='portal_appl_applica_0ff210_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolvacancy',
            index=models.Index(fields=['is_open', 'sector', 'gender'], name='portal_scho_is_open_488623_idx'),
        ),
    ]
