# Generated by Django 5.2.8 on 2026-03-05 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_applicant_created_at_applicant_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('closed_message', models.CharField(blank=True, default='التقديم مغلق حالياً.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
