# Generated by Django 5.2.8 on 2026-03-07 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_portalwindow'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='description',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='portalwindow',
            name='new_only_message',
            field=models.CharField(blank=True, default='التقديم متاح حالياً للمتقدمين الجدد فقط.', max_length=255),
        ),
        migrations.AddField(
            model_name='portalwindow',
            name='official_only_message',
            field=models.CharField(blank=True, default='التقديم متاح حالياً للوكلاء الرسميين فقط.', max_length=255),
        ),
        migrations.AddField(
            model_name='portalwindow',
            name='phase',
            field=models.CharField(choices=[('closed', 'مغلق'), ('official_only', 'الوكلاء الرسميون فقط'), ('new_only', 'المتقدمون الجدد فقط')], db_index=True, default='closed', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolvacancy',
            name='reserved_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_vacancies', to='portal.application'),
        ),
        migrations.AddField(
            model_name='schoolvacancy',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['description'], name='portal_appl_descrip_e28dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolvacancy',
            index=models.Index(fields=['reserved_application'], name='portal_scho_reserve_ded6db_idx'),
        ),
    ]
