# Generated by Django 5.2.8 on 2026-03-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_applicant_description_portalwindow_new_only_message_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='applicant',
            name='portal_appl_descrip_e28dd7_idx',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='description',
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['current_job'], name='portal_appl_current_5f515f_idx'),
        ),
    ]
