# Generated by Django 5.2.8 on 2026-04-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_remove_applicant_portal_appl_descrip_e28dd7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalwindow',
            name='all_message',
            field=models.CharField(blank=True, default='التقديم متاح حالياً للجميع.', max_length=255),
        ),
        migrations.AlterField(
            model_name='portalwindow',
            name='phase',
            field=models.CharField(choices=[('closed', 'مغلق'), ('official_only', 'الوكلاء الرسميون فقط'), ('new_only', 'المتقدمون الجدد فقط'), ('all', 'الجميع (الوكلاء الرسميون + المتقدمون الجدد)')], db_index=True, default='closed', max_length=20),
        ),
    ]
