# Generated by Django 5.2.8 on 2026-05-08 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_portalwindow_all_message_alter_portalwindow_phase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='no_preferences_ack_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت إقرار الإرسال دون رغبات'),
        ),
        migrations.AddField(
            model_name='application',
            name='no_preferences_ack_text',
            field=models.TextField(blank=True, default='', verbose_name='نص إقرار الإرسال دون رغبات'),
        ),
        migrations.AddField(
            model_name='application',
            name='no_preferences_acknowledged',
            field=models.BooleanField(db_index=True, default=False, verbose_name='أقر بالإرسال دون رغبات'),
        ),
        migrations.AddField(
            model_name='application',
            name='preferences_ack_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت إقرار سياسة الرغبات'),
        ),
        migrations.AddField(
            model_name='application',
            name='preferences_ack_text',
            field=models.TextField(blank=True, default='', verbose_name='نص إقرار سياسة الرغبات'),
        ),
        migrations.AddField(
            model_name='application',
            name='preferences_acknowledged',
            field=models.BooleanField(db_index=True, default=False, verbose_name='أقر بسياسة الرغبات'),
        ),
        migrations.AddField(
            model_name='application',
            name='submission_policy_version',
            field=models.CharField(blank=True, default='v1', max_length=50, verbose_name='إصدار سياسة الإقرار'),
        ),
        migrations.AddField(
            model_name='application',
            name='submission_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='لقطة الإرسال'),
        ),
        migrations.AddField(
            model_name='application',
            name='submitted_prefs_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الرغبات وقت الإرسال'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['preferences_acknowledged'], name='portal_appl_prefere_ba8d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['no_preferences_acknowledged'], name='portal_appl_no_pref_2face1_idx'),
        ),
    ]
