# Generated by Django 5.2.8 on 2026-05-08 22:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_application_no_preferences_ack_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDataIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('field_name', models.CharField(choices=[('full_name', 'الاسم الرباعي'), ('mobile', 'رقم الجوال'), ('gender', 'الجنس'), ('rank', 'الرتبة'), ('sector', 'القطاع'), ('current_job', 'العمل الحالي'), ('current_school', 'المدرسة الحالية'), ('start_date', 'تاريخ المباشرة'), ('other', 'أخرى')], db_index=True, max_length=40, verbose_name='الحقل محل الملاحظة')),
                ('current_value', models.CharField(blank=True, default='', max_length=255, verbose_name='القيمة الحالية وقت البلاغ')),
                ('proposed_value', models.CharField(blank=True, default='', max_length=255, verbose_name='التصحيح المقترح')),
                ('note', models.TextField(blank=True, default='', verbose_name='وصف الملاحظة')),
                ('is_blocking', models.BooleanField(db_index=True, default=False, help_text='تُفعّل للحقول المؤثرة في الشواغر أو المفاضلة مثل القطاع والجنس والمدرسة الحالية.', verbose_name='توقف المتابعة لحين المراجعة')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('allowed', 'لا تؤثر على التقديم / سُمح بالمتابعة'), ('accepted', 'مقبولة'), ('rejected', 'مرفوضة'), ('corrected', 'تم التصحيح')], db_index=True, default='pending', max_length=20, verbose_name='حالة المراجعة')),
                ('applicant_snapshot', models.JSONField(blank=True, default=dict, verbose_name='لقطة بيانات المتقدم وقت البلاغ')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='المتصفح')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='ملاحظة الإدارة')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_issues', to='portal.applicant', verbose_name='المتقدم')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_issues', to='portal.application', verbose_name='الطلب')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applicant_data_issues', to=settings.AUTH_USER_MODEL, verbose_name='راجع بواسطة')),
            ],
            options={
                'verbose_name': 'ملاحظة بيانات',
                'verbose_name_plural': 'ملاحظات البيانات',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'is_blocking'], name='portal_appl_status_8d35fe_idx'), models.Index(fields=['applicant', 'status'], name='portal_appl_applica_a210b4_idx'), models.Index(fields=['field_name', 'status'], name='portal_appl_field_n_1491dc_idx'), models.Index(fields=['created_at'], name='portal_appl_created_99d300_idx')],
            },
        ),
    ]
