# Generated by Django 5.2.8 on 2026-05-08 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_add_applicant_data_issues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdataissue',
            name='followup_window_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='نهاية مهلة الاستكمال الخاصة'),
        ),
        migrations.AddField(
            model_name='applicantdataissue',
            name='followup_window_granted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='وقت فتح مهلة الاستكمال الخاصة'),
        ),
        migrations.AddField(
            model_name='applicantdataissue',
            name='followup_window_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_applicant_data_issue_followup_windows', to=settings.AUTH_USER_MODEL, verbose_name='فتح مهلة الاستكمال بواسطة'),
        ),
        migrations.AddField(
            model_name='applicantdataissue',
            name='followup_window_note',
            field=models.TextField(blank=True, default='', verbose_name='ملاحظة مهلة الاستكمال'),
        ),
        migrations.AddField(
            model_name='applicantdataissue',
            name='protected_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='وقت حفظ حق الاستكمال'),
        ),
        migrations.AddField(
            model_name='applicantdataissue',
            name='protects_followup_right',
            field=models.BooleanField(db_index=True, default=False, help_text='يُفعّل عندما يرفع المتقدم ملاحظة مؤثرة أثناء فترة التقديم؛ بحيث لا يتضرر إذا تأخرت مراجعة الإدارة إلى ما بعد إغلاق البوابة.', verbose_name='يحفظ حق الاستكمال'),
        ),
        migrations.AddIndex(
            model_name='applicantdataissue',
            index=models.Index(fields=['protects_followup_right', 'status'], name='portal_appl_protect_0fa1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantdataissue',
            index=models.Index(fields=['followup_window_expires_at'], name='portal_appl_followu_c2bc45_idx'),
        ),
    ]
